/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buysale4u.Ventanas.paneles;

import buysale4u.Ventanas.MostrarArticulo;
import buysale4u.control.ControlArticulos;
import entidades.Articulo;
import entidades.ArticuloFinal;
import java.awt.Dialog;
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author PedroFB
 */
public class Articulos extends javax.swing.JPanel {

    
    Dialog galeria;

    /**
     * Creates new form Articulos
     */
    public Articulos(Frame parent) {
        initComponents();
        
        try {
            Articulo[] array = ControlArticulos.listar();

            ControlArticulos.completarArticulo(lista, array);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(parent, "Error: No se pudo encontrar articulos. \n Conexion fallida");
        }
        if (lista.getModel()== null) {
            JOptionPane.showMessageDialog(parent, "actualmente no se encuentran anuncios de articulos");
        }

        lista.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int indice = lista.getSelectedIndex();
                ControlArticulos.seleccionado = (ArticuloFinal) lista.getModel().getElementAt(indice);
                galeria = new MostrarArticulo(parent, true);
                galeria.setVisible(true);

            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lista);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<ArticuloFinal> lista;
    // End of variables declaration//GEN-END:variables
}
