/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buysale4u.Ventanas.paneles;

import buysale4u.control.Login;
import conexionWebService.Constantes;
import conexionWebService.HttpRequest;

/**
 *
 * @author PedroFB
 */
public class DatosPersonales extends javax.swing.JPanel {

    /**
     * Creates new form DatosPersonales
     */
    public DatosPersonales() {
        initComponents();
        nombre.setText(Login.u.getNombre());
        apellidos.setText(Login.u.getApellidos());
        email.setText(Login.u.getEmail());
        contraseña.setText(Login.u.getContraseña());
        nombre.setEditable(false);
        apellidos.setEditable(false);
        email.setEditable(false);
        contraseña.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        checkNombre = new javax.swing.JCheckBox();
        checkApellidos = new javax.swing.JCheckBox();
        checkContraseña = new javax.swing.JCheckBox();
        nombre = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        contraseña = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Email");

        jLabel4.setText("Contraseña");

        checkNombre.setToolTipText("");
        checkNombre.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkNombreStateChanged(evt);
            }
        });
        checkNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNombreActionPerformed(evt);
            }
        });

        checkApellidos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkApellidosStateChanged(evt);
            }
        });

        checkContraseña.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkContraseñaStateChanged(evt);
            }
        });

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel5.setText("Marque la casilla del campo que desea modificar");

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email)
                            .addComponent(apellidos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkApellidos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 24, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contraseña)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkContraseña)))
                .addGap(170, 170, 170))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(checkNombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkApellidos))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(checkContraseña)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addComponent(jButton1)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5)
                        .addGap(262, 262, 262))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNombreActionPerformed

    }//GEN-LAST:event_checkNombreActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void checkNombreStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkNombreStateChanged
        if (nombre.isEditable()) {
            nombre.setEditable(false);
        } else if (!nombre.isEditable()) {
            nombre.setEditable(true);

        }
    }//GEN-LAST:event_checkNombreStateChanged

    private void checkApellidosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkApellidosStateChanged
        if (apellidos.isEditable()) {
            apellidos.setEditable(false);
        } else if (!apellidos.isEditable()) {
            apellidos.setEditable(true);

        }    }//GEN-LAST:event_checkApellidosStateChanged

    private void checkContraseñaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkContraseñaStateChanged
        if (contraseña.isEditable()) {
            contraseña.setEditable(false);
        } else if (!contraseña.isEditable()) {
            contraseña.setEditable(true);

        }
    }//GEN-LAST:event_checkContraseñaStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String cadena = null;
        if (checkNombre.isSelected()) {
            if (cadena.isEmpty()) {
                cadena = "?nombre=" + nombre.getText();

            } else {
                cadena = "&nombre=" + nombre.getText();
            }
        }
        if (checkApellidos.isSelected()) {
            if (cadena.isEmpty()) {
                cadena = "?apellidos=" + apellidos.getText();

            } else {
                cadena = "&apellidos=" + apellidos.getText();
            }
        }
        if (checkContraseña.isSelected()) {
            if (cadena.isEmpty()) {
                cadena = "?pass=" + contraseña.getText();

            } else {
                cadena = "&pass=" + contraseña.getText();
            }
        }

        enviar_valores(cadena);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void enviar_valores(String cadena) {

        HttpRequest.GET_REQUEST(Constantes.URL_ACTUALIZAR_USUARIO+cadena);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidos;
    private javax.swing.JCheckBox checkApellidos;
    private javax.swing.JCheckBox checkContraseña;
    private javax.swing.JCheckBox checkNombre;
    private javax.swing.JTextField contraseña;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
