/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buysale4u.Ventanas.paneles;

import buysale4u.Ventanas.MostrarArticulo;
import buysale4u.control.ControlArticulos;
import entidades.Articulo;
import java.awt.Dialog;
import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author PedroFB
 */
public class MisArticulos extends javax.swing.JPanel {
 JList<Articulo> listaArticulos;
    Dialog galeria;

    /**
     * Creates new form Articulos
     */
    public MisArticulos(Frame parent) {
        initComponents();

        DefaultListModel modelo = null;
        listaArticulos = new JList<>();
        try {
            Articulo[] array = ControlArticulos.listar();

            ControlArticulos.completarArticulo(listaArticulos, array);
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (modelo == null) {
            JOptionPane.showMessageDialog(parent, "actualmente no se encuentran anuncios de articulos");
        }

        listaArticulos.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int indice = listaArticulos.getSelectedIndex();
                ControlArticulos.seleccionado = listaArticulos.getModel().getElementAt(indice);
                galeria = new MostrarArticulo((Frame) getParent(), true);
                galeria.setVisible(true);

            }

        });

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
