
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buysale4u.swing.articulos;

import buysale4u.swing.galeria.MostrarArticulo;
import buysale4u.control.ControlArticulos;
import entidades.Articulo;
import entidades.ArticuloFinal;
import java.awt.Dialog; 
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 * Interfaz grafica destinada a renderizar una lista de todos los articulos a la
 * venta por los distintos usuarios
 *
 * @author PedroFB
 */
public class Articulos extends javax.swing.JPanel {

    Dialog galeria;

   /**
    * 
    * @param parent Frame 
    */
    public Articulos(Frame parent) {
        initComponents();

        try {
            //inicializamos un array de Articulos e introducimos los valores de la BD
            Articulo[] array = ControlArticulos.listar(false);
            //Introducimos los datos de los articulos en el modelo de la lista
            ControlArticulos.completarArticulo(lista, array);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(parent, "Error: No se pudo encontrar articulos. \n Conexion fallida");
        }
        //comprobamos si los datos se han cargado correctamente en el modelo
        if (lista.getModel() == null) {
            JOptionPane.showMessageDialog(parent, "actualmente no se encuentran anuncios de articulos");
        }
        //añadimos un control ante un evento del JList
        lista.addListSelectionListener(new ListSelectionListener() {
            @Override
            //funcion a realizar cuando seleccionamos un elemento del JList
            public void valueChanged(ListSelectionEvent e) {
                //guardamos el indice del elemento seleccionado en una nueva variable
                int indice = lista.getSelectedIndex();
                //Guardamos el objeto seleccionado en la variable local de la clase ControlArticulos
                ControlArticulos.seleccionado = (ArticuloFinal) lista.getModel().getElementAt(indice);
                //Creamos un nuevo dialog con el constructor de la clase MostrarArticulo.java
                galeria = new MostrarArticulo(parent, true,false);

                galeria.setVisible(true);

            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lista);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<ArticuloFinal> lista;
    // End of variables declaration//GEN-END:variables
}
